import { Car, Mechanic, ModificationService, } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Sam',
    email: 'admin1@gmail.com',
    password:'password123',
    role: 'admin',
  },
    {
    id: '2',
    name: 'Jenil dala',
    email: 'jd@gmail.com',
    password: 'password123',
    role: 'user',
  },
  {
    id: '3',
    name: 'Saksham walia',
    email: 'sw@gmail.com',
    password:'password456',
    role: 'user',
  },
  {
    id: '4',
    name: 'Drashti',
    email: 'dv@gmail.com',
    password:'password789',
    role: 'user',
  },

  {
    id: '5',
    name: 'Akshat',
    email: 'akshat@advancecarhub.com',
    password:'password123',
    role: 'mechanic',
  },
  {
    id: '6',
    name: 'Naishy',
    email: 'naishy@advancecarhub.com',
    password:'password456',
    role: 'mechanic',
  },
  {
    id: '7',
    name: 'Aarif',
    email: 'aarif@advancecarhub.com',
    password:'password789',
    role: 'mechanic',
  },
  {
    id: '8',
    name: 'Robert Martinez',
    email: 'robert.martinez@advancecarhub.com',
    password:'password012',
    role: 'mechanic',
  },
];




export const cars: Car[] = [
  {
    id: '1',
    title: '2019 Toyota Camry XSE',
    price: 4225000,
    year: 2019,
    make: 'Toyota',
    model: 'Camry',
    mileage: 35000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: 'Well-maintained Toyota Camry XSE with low mileage. Features include leather seats, sunroof, and advanced safety features.',
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80'
    ],
    sellerId: '1',
    sellerName: 'Om Patel',
    createdAt: '2023-06-15T10:30:00Z',
    forSale: true,
  },
  {
    id: '2',
    title: '2020 Honda Civic Sport',
    price: 2222500,
    year: 2020,
    make: 'Honda',
    model: 'Civic',
    mileage: 28000,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    description: 'Sporty Honda Civic in excellent condition. One owner, regularly serviced, and includes premium sound system.',
    images: [
      'https://tse1.mm.bing.net/th?id=OIP.eRPSPy-tYD0yz7Hi8JRiQQHaEK&pid=Api&P=0&h=180',
      'https://i.pinimg.com/originals/3f/07/5b/3f075b31b706fb222c9fb9220db18cf5.jpg'
    ],
    sellerId: '2',
    sellerName: 'Nihar Gandhi ',
    createdAt: '2023-07-20T14:45:00Z',
    forSale: true,
  },
  {
    id: '3',
    title: '2018 Ford Mustang GT',
    price: 3235000,
    year: 2018,
    make: 'Ford',
    model: 'Mustang',
    mileage: 42000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: 'Powerful Ford Mustang GT with 5.0L V8 engine. Includes performance package and premium interior.',
    images: [
      'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1494905998402-395d579af36f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80'
    ],
    sellerId: '3',
    sellerName: 'Jaikrit saxena',
    createdAt: '2023-05-10T09:15:00Z',
    forSale: true,
  },
  {
    id: '4',
    title: '2022 Mclaren P1',
    price: 9195000,
    year: 2021,
    make: 'Mclaren',
    model: 'P1',
    mileage: 22000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: 'Experience the pinnacle of performance and luxury with McLaren – cutting-edge design, breathtaking speed, and precision engineering for the ultimate driving thrill.',
    images: [
      'https://1cars.org/wp-content/uploads/2021/04/McLaren-P1-10.jpg',
      'https://s.yimg.com/zb/imgv1/f49487e8-b1a7-36b6-a035-7461f851f09f/t_500x300'],
    sellerId: '4',
    sellerName: 'Ansh',
    createdAt: '2022-03-10T09:11:00Z',
    forSale: true,
  },
  {
    id: '5',
    title: 'Lamborghini Huracan',
    price: 5535000,
    year: 2024,
    make: 'Lamborghini',
    model: 'Huracan',
    mileage: 23000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: 'Experience the thrill of the Lamborghini Huracán—a masterpiece of speed, luxury, and cutting-edge performance, now available for sale! 🚀🔥',
    images: [
      'https://tse2.mm.bing.net/th?id=OIP.CBK58_-lVUvjz2RvsIlQFwHaEK&pid=Api&P=0&h=180',
      'https://tse2.mm.bing.net/th?id=OIP.b-SuRmxLoMwDUFt0MkZhiAHaEK&pid=Api&P=0&h=180'],
    sellerId: '5',
    sellerName: 'Harshal Gulati',
    createdAt: '2024-12-12T01:11:00Z',
    forSale: true,
  },
  {
    id: '6',
    title: 'Hummer GMC',
    price: 9999999,
    year: 2024,
    make: 'Hummer',
    model: 'GMC',
    mileage: 55000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    description: 'Experience the future of electric off-roading with the Hummer EV—powerful, rugged, and built for adventure.',
    images: [
      'https://s.yimg.com/zb/imgv1/51643a3b-89d2-33aa-b3ea-50c2c62d1bf8/t_500x300',
      'https://cdn.bigboytoyz.com/newcar/files/upload/brandmodel/1619434965993-2024_gmc_hummer_ev_suv_1_1600x1200.jpg'],
    sellerId: '6',
    sellerName: 'Priyanshu',
    createdAt: '2024-12-25T11:11:00Z',
    forSale: true,
  },

  {
    id: '7',
    title: 'Mercedes AMG-G63',
    price: 5453000,
    year: 2024,
    make: 'Mercedes',
    model: 'AMG-G63 ',
    mileage: 34000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: 'Luxury and performance redefined – Own the iconic Mercedes-AMG G63, a powerhouse SUV with unmatched style and strength.',
    images: [
    'https://s1.cdn.autoevolution.com/images/news/gallery/performmaster-made-mercedes-amg-g63-look-even-more-menacing_1.jpg',
    'https://images.autodaily.com.au/2022/03/2022-Mercedes-AMG-G63-Edition-55-2-1920x1157.jpg'],
    sellerId: '7',
    sellerName: 'Anirud Singh',
    createdAt: '2018-2-25T03:10:00Z',
    forSale: true,
  },
  {
    id: '8',
    title: 'Mercedes S-Class',
    price: 3443000,
    year: 2024,
    make: 'Mercedes',
    model: 'S-Class ',
    mileage: 54000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: ' Mercedes-Benz S-Class – where innovation meets elegance for an unparalleled driving experience',
    images: [
      'https://i0.wp.com/www.mrpinglife.com/wp-content/uploads/2017/09/Exterior.jpg?resize=6000%2C4000&ssl=1',
      'https://www.marinoperformancemotors.com/imagetag/12839/6/l/Used-2017-Mercedes-Benz-S-Class-S-550.jpg'],
    sellerId: '8',
    sellerName: 'Sam Patel',
    createdAt: '2018-02-25T03:10:00Z',
    forSale: true,
  },
  {
    id: '9',
    title: 'Proche 911 GT3',
    price: 9999999,
    year: 2019,
    make: 'Proche',
    model: '911 GT3 ',
    mileage: 50000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    description: ' The Porsche 911 GT3 is a high-performance sports car renowned for its precision handling, powerful flat-six engine, and track-focused design. 🚀🔥',
    images: [
      'https://tse4.mm.bing.net/th?id=OIP.U0tR5wZ0HiR8BXswqPu2KwHaEK&pid=Api&P=0&h=180',
      'https://files.porsche.com/filestore/image/multimedia/none/992-gt3-rs-modelimage-sideshot/model/cfbb8ed3-1a15-11ed-80f5-005056bbdc38/porsche-model.png'
    ],
    sellerId: '9',
    sellerName: 'S.walia',
    createdAt: '2020-11-25T04:10:00Z',
    forSale: true,
  },
];

export const mechanics: Mechanic[] = [
  {
    id: '1',
    name: 'Akshat',
    specialization: 'Engine Specialist',
    experience: 15,
    rating: 4.8,
    image: 'https://th.bing.com/th/id/R.4eae69983e0e789682ad445396345e8a?rik=WGN7I2JIsmSiBA&riu=http%3a%2f%2fgwrench.com%2fwp-content%2fuploads%2f2020%2f12%2fVistaCarMechanic.jpeg&ehk=fIr1oWPGfbODcKpiWJgz8WWM32dxHrVmdanyD2ifQEM%3d&risl=&pid=ImgRaw&r=0',
    contact: '+91 (555) 123-4567',
    description: 'Specialized in high-performance engine tuning and repairs with 15 years of experience working with luxury and sports cars.',
  },
  {
    id: '2',
    name: 'Naishy',
    specialization: 'Electrical Systems',
    experience: 10,
    rating: 4.7,
    image: 'https://www.shutterstock.com/image-photo/portrait-shot-female-mechanic-working-260nw-1711144597.jpg',
    contact: '+91 (555) 987-6543',
    description: 'Expert in automotive electrical systems and diagnostics. Certified in advanced automotive electronics and computer systems.',
  },
  {
    id: '3',
    name: 'Aarif',
    specialization: 'Custom Modifications',
    experience: 12,
    rating: 4.9,
    image: 'https://mymodernmotors.com/images/services/Under%20Chassis%20Rust%20Coating.jpg',
    contact: '+91 (555) 456-7890',
    description: 'Specializes in custom car modifications including body kits, performance upgrades, and interior customizations.',
  },
  {
    id: '4',
    name: 'Robert Martinez',
    specialization: 'Transmission Expert',
    experience: 18,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    contact: '+91 (555) 234-5678',
    description: 'Master technician specializing in manual and automatic transmission repairs and upgrades for all vehicle types.',
  },
];

export const modificationServices: ModificationService[] = [
  {
    id: '1',
    name: 'Performance Tuning',
    description: 'Engine tuning to increase horsepower and torque while maintaining reliability.',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    category: 'Performance',
  },
  {
    id: '2',
    name: 'Custom Exhaust System',
    description: 'High-performance exhaust systems designed to improve flow and sound.',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    category: 'Performance',
  },
  {
    id: '3',
    name: 'Suspension Upgrade',
    description: 'Improve handling and ride quality with premium suspension components.',
    price: 20000,
    image: 'https://images.unsplash.com/photo-1537984822441-cff330075342?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    category: 'Performance',
  },
  {
    id: '4',
    name: 'Interior Customization',
    description: 'Premium leather upholstery, custom dashboard, and ambient lighting.',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    category: 'Aesthetics',
  },
  {
    id: '5',
    name: 'Body Kit Installation',
    description: 'Custom body kits to enhance the appearance and aerodynamics of your vehicle.',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    category: 'Aesthetics',
  },
  {
    id: '6',
    name: 'Advanced Audio System',
    description: 'High-end speakers, amplifiers, and subwoofers for the ultimate sound experience.',
    price: 25000,
    image: 'https://tse3.mm.bing.net/th?id=OIP.5WW32XVsz8HzKYVSjB7NwQHaEK&pid=Api&P=0&h=180',
    category: 'Electronics',
  },
];